apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-gateway
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: frontend-gateway
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/frontend-gateway:PLACEHOLDER
