images:
  - name: adservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/adservice
    newTag: 9ea9844

  - name: cartservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/cartservice
    newTag: 9ea9844

  - name: checkoutservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/checkoutservice
    newTag: 9ea9844

  - name: currencyservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/currencyservice
    newTag: 9ea9844

  - name: emailservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/emailservice
    newTag: 9ea9844

  - name: frontend-ui
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/frontend-ui
    newTag: 9ea9844

  - name: paymentservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/paymentservice
    newTag: 9ea9844

  - name: productcatalogservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/productcatalogservice
    newTag: 9ea9844

  - name: recommendationservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/recommendationservice
    newTag: 9ea9844

  - name: shippingservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/shippingservice
    newTag: 9ea9844

  - name: shoppingassistantservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/shoppingassistantservice
    newTag: 9ea9844

