apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: adservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: cartservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: checkoutservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: currencyservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: emailservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: frontend-gateway
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: frontend-ui
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: paymentservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: productcatalogservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: recommendationservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: shippingservice
      labels:
        app.kubernetes.io/managed-by: argocd

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: shoppingassistantservice
      labels:
        app.kubernetes.io/managed-by: argocd
