apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: adservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: cartservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: checkoutservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: currencyservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: emailservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: frontend-ui
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: paymentservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: productcatalogservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: recommendationservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: shippingservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-sa
  namespace: shoppingassistantservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::931058976119:role/prod-ready-eks-irsa-role
