apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recommendationservice

resources:
  - ../../../base/recommendationservice.yaml
  - sa-ecr.yaml

patches:
  - path: ../patch-use-ecr-sa.yaml
    target:
      kind: Deployment

images:
  - name: recommendationservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/recommendationservice
    newTag: "<IMAGE_TAG>"
