apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: shippingservice
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/shippingservice:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 50051
