sonar.projectKey=recommendationservice
sonar.projectName=recommendationservice
sonar.sources=.
sonar.sourceEncoding=UTF-8

# IMPORTANT — avoids all duplicate-file indexing
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/genproto/**,**/coverage/**,**/*.md,LICENSE
