# Send logs to Loki
loki:
  serviceName: loki
  servicePort: 3100
  serviceNamespace: monitoring

# Configure Promtail scraping
config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

  snippets:
    pipelineStages:
      - cri: {}

  serverPort: 3101

  scrape_configs:
    - job_name: kubernetes-pods
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - action: drop
          regex: "kube-system"
          source_labels: [__meta_kubernetes_namespace]
