apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adservice

resources:
  - ../../../base/adservice.yaml

patches:
  - path: ../patch-use-ecr-sa.yaml
    target:
      kind: Deployment

images:
  - name: adservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/adservice
    newTag: "<IMAGE_TAG>"
