apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: emailservice
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/emailservice:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
