apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    targetRevision: HEAD
    path: k8s-manifests/argocd-apps/dev
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  # ALL 12 CHILD APPLICATIONS
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/adservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/cartservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/checkoutservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/currencyservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/emailservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/frontend-ui.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/paymentservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/productcatalog.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/recommendationservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/shippingservice.yaml
  - repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    path: k8s-manifests/argocd-apps/dev/shoppingassistant.yaml
