apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkoutservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: checkoutservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
