apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-gateway
  namespace: frontend-gateway
  labels:
    app: frontend-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-gateway
  template:
    metadata:
      labels:
        app: frontend-gateway
    spec:
      serviceAccountName: ecr-access-sa
      containers:
      - name: frontend-gateway
        image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/frontend-gateway:latest
        ports:
        - containerPort: 8081
        env:
        - name: PRODUCT_SERVICE_ADDR
          value: "productcatalogservice.productcatalogservice:3550"
        - name: CART_SERVICE_ADDR
          value: "cartservice.cartservice:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice.recommendationservice:8085"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice.shippingservice:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice.checkoutservice:5050"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice.currencyservice:7000"
        - name: AD_SERVICE_ADDR
          value: "adservice.adservice:9555"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice.emailservice:8080"
        - name: PORT
          value: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-gateway
  namespace: frontend-gateway
  labels:
    app: frontend-gateway
spec:
  type: ClusterIP
  selector:
    app: frontend-gateway
  ports:
  - name: http
    port: 8081
    targetPort: 8081
