apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - namespace.yaml

  # Service accounts directory (contains all SA files)
  - service-accounts

  # Each microservice directory (each contains deployment.yaml + service.yaml)
  - adservice
  - cartservice
  - checkoutservice
  - currencyservice
  - emailservice
  - frontend-gateway
  - frontend-ui
  - paymentservice
  - productcatalogservice
  - recommendationservice
  - shippingservice
  - shoppingassistantservice
