apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: recommendationservice
spec:
  selector:
    app: recommendationservice
  ports:
    - port: 8080
      targetPort: 8080
