apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: paymentservice
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/paymentservice:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 50051
