apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: paymentservice
          image: paymentservice:latest
          ports:
            - containerPort: 50051
