apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frontend-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: httpsgithub.com/kapilkumaria/production-ready-gcp-microservices-eks-devsecops.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-frontend-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
