sonar.projectKey=cartservice
sonar.projectName=cartservice

# C# source files
sonar.sources=.

# There are NO tests for cartservice
sonar.tests=
sonar.test.inclusions=
sonar.test.exclusions=**/*.cs

# Coverage (will be uploaded if exists)
sonar.cs.opencover.reportsPaths=coverage.opencover.xml

# Exclusions (same as global)
sonar.exclusions=**/obj/**,**/bin/**,**/node_modules/**,**/build/**,**/.gradle/**
