apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - grafana-datasources.yaml
  - grafana-dashboard-providers.yaml
  - grafana-dashboards-volume.yaml

# Generate one ConfigMap per dashboard file WITHOUT embedding into annotations
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/cluster-monitoring.json
      - dashboards/global-overview.json
      - dashboards/loki-logs-browser.json
      - dashboards/microservices-golden-signals.json
      - dashboards/namespace-overview.json
      - dashboards/node-exporter-full.json
      - dashboards/nodes-overview.json
      - dashboards/workloads-overview.json

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    grafana_dashboard: "1"
