apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Base Grafana resources (MUST include deployment!)
  - grafana-datasources.yaml
  - grafana-dashboard-providers.yaml
  - grafana-dashboards-volume.yaml
  - grafana-deployment.yaml                


configMapGenerator:
  - name: dashboard-cluster-monitoring
    files:
      - dashboards/cluster-monitoring.json

  - name: dashboard-global-overview
    files:
      - dashboards/global-overview.json

  - name: dashboard-loki-logs-browser
    files:
      - dashboards/loki-logs-browser.json

  - name: dashboard-microservices-golden-signals
    files:
      - dashboards/microservices-golden-signals.json

  - name: dashboard-namespace-overview
    files:
      - dashboards/namespace-overview.json

  - name: dashboard-nodes-overview
    files:
      - dashboards/nodes-overview.json

  - name: dashboard-workloads-overview
    files:
      - dashboards/workloads-overview.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
