apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emailservice

resources:
  - ../../base/emailservice.yaml

patches:
  - ../patch-use-ecr-sa.yaml

images:
  - name: emailservice
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/emailservice
    newTag: "<IMAGE_TAG>"
