service:
  type: ClusterIP
  port: 9100

rbac:
  create: true

serviceAccount:
  create: true
  name: node-exporter

resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 30Mi

prometheus:
  monitor:
    enabled: true
    additionalLabels:
      release: prometheus
    namespace: monitoring
