apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      serviceAccountName: ecr-access-ui-sa
      containers:
        - name: frontend-ui
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/frontend-ui:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80
