syntax = "proto3";

package productcatalog;

option go_package = "github.com/GoogleCloudPlatform/microservices-demo/src/productcatalogservice/genproto";

message Empty {}

service ProductCatalogService {
  rpc ListProducts(Empty) returns (ListProductsResponse);
  rpc GetProduct(GetProductRequest) returns (Product);
  rpc SearchProducts(SearchProductsRequest) returns (SearchProductsResponse);
}

message GetProductRequest {
  string id = 1;
}

message SearchProductsRequest {
  string query = 1;
}

message SearchProductsResponse {
  repeated Product results = 1;
}

message Product {
  string id = 1;
  string name = 2;
  string description = 3;

  string picture = 4;                // REQUIRED by Go code
  repeated string categories = 5;     // REQUIRED by Go code

  Money price_usd = 6;                // REQUIRED by Go code
}

message Money {
  string currency_code = 1;
  int64 units = 2;
  int32 nanos = 3;
}

message ListProductsResponse {
  repeated Product products = 1;
}
