// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: checkout/checkout.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for placing an order
type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCurrency  string                 `protobuf:"bytes,2,opt,name=user_currency,json=userCurrency,proto3" json:"user_currency,omitempty"` // user-selected currency
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreditCard    *CreditCardInfo        `protobuf:"bytes,4,opt,name=credit_card,json=creditCard,proto3" json:"credit_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_checkout_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_checkout_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserCurrency() string {
	if x != nil {
		return x.UserCurrency
	}
	return ""
}

func (x *PlaceOrderRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PlaceOrderRequest) GetCreditCard() *CreditCardInfo {
	if x != nil {
		return x.CreditCard
	}
	return nil
}

// Response for placing an order
type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ShippingCost  *Money                 `protobuf:"bytes,2,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalCost     *Money                 `protobuf:"bytes,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_checkout_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_checkout_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetShippingCost() *Money {
	if x != nil {
		return x.ShippingCost
	}
	return nil
}

func (x *PlaceOrderResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlaceOrderResponse) GetTotalCost() *Money {
	if x != nil {
		return x.TotalCost
	}
	return nil
}

// Represents a single ordered item
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CartItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Cost          *Money                 `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_checkout_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_checkout_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItem) GetItem() *CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *OrderItem) GetCost() *Money {
	if x != nil {
		return x.Cost
	}
	return nil
}

var File_checkout_checkout_proto protoreflect.FileDescriptor

const file_checkout_checkout_proto_rawDesc = "" +
	"\n" +
	"\x17checkout/checkout.proto\x12\vhipstershop\x1a\x1bproductcatalog/common.proto\x1a\x0fcart/cart.proto\"\xbf\x01\n" +
	"\x11PlaceOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\ruser_currency\x18\x02 \x01(\tR\fuserCurrency\x12.\n" +
	"\aaddress\x18\x03 \x01(\v2\x14.hipstershop.AddressR\aaddress\x12<\n" +
	"\vcredit_card\x18\x04 \x01(\v2\x1b.hipstershop.CreditCardInfoR\n" +
	"creditCard\"\xc9\x01\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x127\n" +
	"\rshipping_cost\x18\x02 \x01(\v2\x12.hipstershop.MoneyR\fshippingCost\x12,\n" +
	"\x05items\x18\x03 \x03(\v2\x16.hipstershop.OrderItemR\x05items\x121\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\v2\x12.hipstershop.MoneyR\ttotalCost\"^\n" +
	"\tOrderItem\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.hipstershop.CartItemR\x04item\x12&\n" +
	"\x04cost\x18\x02 \x01(\v2\x12.hipstershop.MoneyR\x04cost2b\n" +
	"\x0fCheckoutService\x12O\n" +
	"\n" +
	"PlaceOrder\x12\x1e.hipstershop.PlaceOrderRequest\x1a\x1f.hipstershop.PlaceOrderResponse\"\x00B\"\n" +
	"\vhipstershopP\x01Z\x11frontend/genprotob\x06proto3"

var (
	file_checkout_checkout_proto_rawDescOnce sync.Once
	file_checkout_checkout_proto_rawDescData []byte
)

func file_checkout_checkout_proto_rawDescGZIP() []byte {
	file_checkout_checkout_proto_rawDescOnce.Do(func() {
		file_checkout_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkout_checkout_proto_rawDesc), len(file_checkout_checkout_proto_rawDesc)))
	})
	return file_checkout_checkout_proto_rawDescData
}

var file_checkout_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_checkout_checkout_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),  // 0: hipstershop.PlaceOrderRequest
	(*PlaceOrderResponse)(nil), // 1: hipstershop.PlaceOrderResponse
	(*OrderItem)(nil),          // 2: hipstershop.OrderItem
	(*Address)(nil),            // 3: hipstershop.Address
	(*CreditCardInfo)(nil),     // 4: hipstershop.CreditCardInfo
	(*Money)(nil),              // 5: hipstershop.Money
	(*CartItem)(nil),           // 6: hipstershop.CartItem
}
var file_checkout_checkout_proto_depIdxs = []int32{
	3, // 0: hipstershop.PlaceOrderRequest.address:type_name -> hipstershop.Address
	4, // 1: hipstershop.PlaceOrderRequest.credit_card:type_name -> hipstershop.CreditCardInfo
	5, // 2: hipstershop.PlaceOrderResponse.shipping_cost:type_name -> hipstershop.Money
	2, // 3: hipstershop.PlaceOrderResponse.items:type_name -> hipstershop.OrderItem
	5, // 4: hipstershop.PlaceOrderResponse.total_cost:type_name -> hipstershop.Money
	6, // 5: hipstershop.OrderItem.item:type_name -> hipstershop.CartItem
	5, // 6: hipstershop.OrderItem.cost:type_name -> hipstershop.Money
	0, // 7: hipstershop.CheckoutService.PlaceOrder:input_type -> hipstershop.PlaceOrderRequest
	1, // 8: hipstershop.CheckoutService.PlaceOrder:output_type -> hipstershop.PlaceOrderResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_checkout_checkout_proto_init() }
func file_checkout_checkout_proto_init() {
	if File_checkout_checkout_proto != nil {
		return
	}
	file_productcatalog_common_proto_init()
	file_cart_cart_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkout_checkout_proto_rawDesc), len(file_checkout_checkout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_checkout_proto_goTypes,
		DependencyIndexes: file_checkout_checkout_proto_depIdxs,
		MessageInfos:      file_checkout_checkout_proto_msgTypes,
	}.Build()
	File_checkout_checkout_proto = out.File
	file_checkout_checkout_proto_goTypes = nil
	file_checkout_checkout_proto_depIdxs = nil
}
