// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: recommendation/recommendation.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for recommendations
type ListRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationsRequest) Reset() {
	*x = ListRecommendationsRequest{}
	mi := &file_recommendation_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsRequest) ProtoMessage() {}

func (x *ListRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*ListRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *ListRecommendationsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// Response containing recommended product IDs
type ListRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationsResponse) Reset() {
	*x = ListRecommendationsResponse{}
	mi := &file_recommendation_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsResponse) ProtoMessage() {}

func (x *ListRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*ListRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *ListRecommendationsResponse) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

var File_recommendation_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_recommendation_proto_rawDesc = "" +
	"\n" +
	"#recommendation/recommendation.proto\x12\vhipstershop\x1a$productcatalog/product_catalog.proto\";\n" +
	"\x1aListRecommendationsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\">\n" +
	"\x1bListRecommendationsResponse\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds2\x83\x01\n" +
	"\x15RecommendationService\x12j\n" +
	"\x13ListRecommendations\x12'.hipstershop.ListRecommendationsRequest\x1a(.hipstershop.ListRecommendationsResponse\"\x00B\"\n" +
	"\vhipstershopP\x01Z\x11frontend/genprotob\x06proto3"

var (
	file_recommendation_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_recommendation_proto_rawDescData []byte
)

func file_recommendation_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_recommendation_proto_rawDesc), len(file_recommendation_recommendation_proto_rawDesc)))
	})
	return file_recommendation_recommendation_proto_rawDescData
}

var file_recommendation_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recommendation_recommendation_proto_goTypes = []any{
	(*ListRecommendationsRequest)(nil),  // 0: hipstershop.ListRecommendationsRequest
	(*ListRecommendationsResponse)(nil), // 1: hipstershop.ListRecommendationsResponse
}
var file_recommendation_recommendation_proto_depIdxs = []int32{
	0, // 0: hipstershop.RecommendationService.ListRecommendations:input_type -> hipstershop.ListRecommendationsRequest
	1, // 1: hipstershop.RecommendationService.ListRecommendations:output_type -> hipstershop.ListRecommendationsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recommendation_recommendation_proto_init() }
func file_recommendation_recommendation_proto_init() {
	if File_recommendation_recommendation_proto != nil {
		return
	}
	file_productcatalog_product_catalog_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_recommendation_proto_rawDesc), len(file_recommendation_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_recommendation_proto_depIdxs,
		MessageInfos:      file_recommendation_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_recommendation_proto = out.File
	file_recommendation_recommendation_proto_goTypes = nil
	file_recommendation_recommendation_proto_depIdxs = nil
}
