syntax = "proto3";

package hipstershop;

// Empty message
message Empty {}

// Checkout request
message CheckoutRequest {
  string user_id = 1;
  string user_currency = 2;
}

// Money representation
message Money {
  string currency_code = 1;
  int64 units = 2;
  int32 nanos = 3;
}

// Order result
message PlaceOrderResponse {
  string order_id = 1;
  Money shipping_cost = 2;
  Money total_cost = 3;
}

// Checkout service definition
service CheckoutService {
  rpc PlaceOrder(CheckoutRequest) returns (PlaceOrderResponse);
}
