apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-gateway
  namespace: default
  labels:
    app: frontend-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-gateway
  template:
    metadata:
      labels:
        app: frontend-gateway
    spec:
      serviceAccountName: ecr-access-gateway-sa
      containers:
        - name: frontend-gateway
          image: frontend-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          
          args:
            - "--product_catalog_service_addr=productcatalogservice.productcatalogservice.svc.cluster.local:3550"
            - "--cart_service_addr=cartservice.cartservice.svc.cluster.local:7070"
            - "--currency_service_addr=currencyservice.currencyservice.svc.cluster.local:7000"
            - "--checkout_service_addr=checkoutservice.checkoutservice.svc.cluster.local:5050"
            - "--recommendation_service_addr=recommendationservice.recommendationservice.svc.cluster.local:8080"
            - "--shipping_service_addr=shippingservice.shippingservice.svc.cluster.local:50051"
            - "--email_service_addr=emailservice.emailservice.svc.cluster.local:8080"
            - "--ad_service_addr=adservice.adservice.svc.cluster.local:9555"
            - "--shoppingassistant_service_addr=shoppingassistantservice.shoppingassistantservice.svc.cluster.local:8080"

