syntax = "proto3";

package hipstershop;

option java_multiple_files = true;
option java_package = "hipstershop";
option go_package = "frontend/genproto";

import "productcatalog/common.proto";
import "cart/cart.proto";

// Request for a shipping quote
message GetQuoteRequest {
  Address address = 1;
  repeated CartItem items = 2;
}

// Response with shipping cost
message GetQuoteResponse {
  Money cost_usd = 1;
}

// Request to ship an order
message ShipOrderRequest {
  Address address = 1;
  repeated CartItem items = 2;
}

// Response for shipping
message ShipOrderResponse {
  string tracking_id = 1;
}

service ShippingService {
  rpc GetQuote(GetQuoteRequest) returns (GetQuoteResponse) {}
  rpc ShipOrder(ShipOrderRequest) returns (ShipOrderResponse) {}
}
