apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - ingress.yaml

# Apply only the image override for frontend-ui
images:
  - name: frontend-ui
    newName: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/frontend-ui
    newTag: "661b424"
