sonar.projectKey=loadgenerator
sonar.projectName=loadgenerator
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/genproto/**,**/coverage/**,**/*.md,LICENSE
