server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # Serve images from /products folder
    location /products/ {
        try_files $uri $uri/ =404;
    }

    # Proxy API calls to frontend-gateway container
    location /api/ {
        proxy_pass http://frontend-gateway:8081;
    }

    # SPA fallback
    location / {
        try_files $uri /index.html;
    }
}
