sonar.projectKey=frontend-ui
sonar.projectName=frontend-ui

# Main code
sonar.sources=src,public

# Tests (this project has NO tests)
sonar.tests=
sonar.test.inclusions=

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# JS Coverage (there is none, so safe)
sonar.javascript.lcov.reportPaths=

# Encoding
sonar.sourceEncoding=UTF-8
