sonar.projectKey=adservice
sonar.projectName=adservice
sonar.sources=.
sonar.language=java
sonar.java.binaries=build/classes/java/main
sonar.java.source=17

# No tests available in this service
sonar.tests=
sonar.test.inclusions=
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml