sonar.projectKey=adservice
sonar.projectName=adservice
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Avoid all duplicate indexing and build issues
sonar.exclusions=**/build/**,**/dist/**,**/node_modules/**,**/.gradle/**,**/genproto/**,LICENSE,**/*.md

# IMPORTANT FOR JAVA WITHOUT BUILD
sonar.java.binaries=.
