apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: currencyservice
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/currencyservice:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 7000
