sonar.projectKey=frontend-gateway
sonar.projectName=frontend-gateway
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/genproto/**,**/coverage/**,**/*.md,LICENSE
