apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: cartservice
          image: 931058976119.dkr.ecr.us-east-1.amazonaws.com/gcp-microservices/cartservice:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 7070
