apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: ecr-access-sa
      containers:
        - name: cartservice
          image: cartservice:latest
          ports:
            - containerPort: 7070
