syntax = "proto3";

package hipstershop;

option go_package = "github.com/production/gcp-microservices/frontend/genproto;genproto";

// Payment service definition.
service PaymentService {
  rpc Charge(ChargeRequest) returns (ChargeResponse) {}
}

// Charge request includes amount and credit card info.
message ChargeRequest {
  Money amount = 1;
  CreditCardInfo credit_card = 2;
}

// ChargeResponse returns a transaction ID to track payment.
message ChargeResponse {
  string transaction_id = 1;
}

// Money is a standard currency+amount message used across services.
message Money {
  string currency_code = 1;
  int32 units = 2;
  int32 nanos = 3;
}

// CreditCardInfo stores cardholder payment details.
message CreditCardInfo {
  string credit_card_number = 1;
  int32 credit_card_cvv = 2;
  int32 credit_card_expiration_month = 3;
  int32 credit_card_expiration_year = 4;
  string billing_address = 5;
}
