name: Simple-Sonar-CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sonar-scan:
    runs-on: self-hosted
    strategy:
      matrix:
        service:
          - checkoutservice
          - adservice
          - currencyservice
          - paymentservice
          - productcatalogservice
          - frontend-ui
          - frontend-gateway
          - cartservice
          - emailservice
          - shoppingassistantservice
          - shippingservice
          - recommendationservice

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Sonar Scanner to PATH
        run: echo "/opt/sonar-scanner/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Verify Scanner
        run: sonar-scanner --version

      - name: Run Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd src/${{ matrix.service }}

          sonar-scanner \
            -Dsonar.projectKey=${{ matrix.service }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=. \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/*.md,LICENSE
