name: Microservices-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: self-hosted

    strategy:
      matrix:
        service:
          [
            "checkoutservice",
            "adservice",
            "currencyservice",
            "paymentservice",
            "productcatalogservice",
            "frontend-ui",
            "frontend-gateway",
            "cartservice",
            "emailservice",
            "shoppingassistantservice",
            "shippingservice",
            "recommendationservice"            
          ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4           

      - name: Add sonar-scanner to PATH
        run: echo "/opt/sonar-scanner/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Check sonar-scanner
        run: |
          which sonar-scanner
          sonar-scanner --version

      - name: Verify Java installed
        run: |
          java -version
          echo $JAVA_HOME

      - name: Build Java service (only adservice)
        if: matrix.service == 'adservice'
        run: |
          cd src/adservice
          ./gradlew compileJava -x shadowJar -x distZip -x distTar    

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          EXTRA_ARGS=""
          if [ "${{ matrix.service }}" = "adservice" ]; then
            EXTRA_ARGS="-Dsonar.java.binaries=src/adservice/build/classes/java/main"
          fi

          sonar-scanner \
            -Dsonar.projectKey=${{ matrix.service }} \
            -Dsonar.sources=src/${{ matrix.service }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            $EXTRA_ARGS

